#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi before the 10th time
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
